gui:
  # Catppuccin Mocha Theme
  theme:
    activeBorderColor:
      - '#89b4fa' # Blue
      - bold
    inactiveBorderColor:
      - '#6c7086' # Overlay0
    optionsTextColor:
      - '#89b4fa' # Blue
    selectedLineBgColor:
      - '#313244' # Surface0
    selectedRangeBgColor:
      - '#313244' # Surface0
    cherryPickedCommitBgColor:
      - '#94e2d5' # Teal
    cherryPickedCommitFgColor:
      - '#89b4fa' # Blue
    unstagedChangesColor:
      - '#f38ba8' # Red
    defaultFgColor:
      - '#cdd6f4' # Text

  # Window settings
  windowSize: 'normal'
  scrollHeight: 2
  scrollPastBottom: true
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  mainPanelSplitMode: 'flexible'
  language: 'auto'
  timeFormat: '02 Jan 06 15:04 MST'
  shortTimeFormat: '15:04'

  # Display settings
  showFileTree: true
  showListFooter: true
  showRandomTip: false
  showBranchCommitHash: true
  showBottomLine: true
  showCommandLog: true
  showIcons: true
  nerdFontsVersion: "3"

  # Commit settings
  commitLength:
    show: true
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false

  # Border style
  border: 'rounded'

git:
  # Paging using delta
  paging:
    colorArg: always
    pager: delta --dark --paging=never --syntax-theme="Catppuccin Mocha"
    useConfig: false

  # Commit settings
  commit:
    signOff: false
    autoWrapCommitMessage: true
    autoWrapWidth: 72

  # Merge settings
  merging:
    manualCommit: false
    args: ''

  # Pull settings
  pull:
    mode: 'merge'

  # Push settings
  skipHookPrefix: WIP
  autoFetch: true
  autoRefresh: true
  fetchAll: true

  # Branch settings
  branchLogCmd: 'git log --graph --color=always --abbrev-commit --decorate --date=relative --pretty=medium {{branchName}} --'
  allBranchesLogCmd: 'git log --graph --all --color=always --abbrev-commit --decorate --date=relative --pretty=medium'
  overrideGpg: false
  disableForcePushing: false
  parseEmoji: true

  # Diff settings
  diffContextSize: 3

os:
  # Editor settings
  editPreset: 'nvim'
  edit: ''
  editAtLine: '{{editor}} +{{line}} {{filename}}'
  editAtLineAndWait: '{{editor}} +{{line}} {{filename}}'
  open: ''
  openLink: ''

  # Copy to clipboard
  copyToClipboardCmd: ''

refresher:
  refreshInterval: 10
  fetchInterval: 60

update:
  method: prompt
  days: 14

confirmOnQuit: false

quitOnTopLevelReturn: false

# Disable mouse by default (use vim keybindings)
disableStartupPopups: true

# Custom commands for web development
customCommands:
  - key: '<c-r>'
    command: 'git rebase -i HEAD~{{ .Form.Count }}'
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'How many commits back?'
        key: 'Count'
        initialValue: '5'

  - key: 'C'
    command: 'git commit --amend --no-edit'
    context: 'files'
    loadingText: 'Amending last commit...'
    description: 'Amend last commit without editing message'

  - key: '<c-p>'
    command: 'git push --force-with-lease'
    context: 'localBranches'
    loadingText: 'Force pushing with lease...'
    description: 'Force push with lease (safer than --force)'

  - key: 'T'
    command: 'git tag -a {{.Form.Tag}} -m "{{.Form.Message}}"'
    context: 'commits'
    prompts:
      - type: 'input'
        title: 'Tag name:'
        key: 'Tag'
      - type: 'input'
        title: 'Tag message:'
        key: 'Message'
    description: 'Create annotated tag'

  - key: 'W'
    command: 'git commit -m "WIP: {{.Form.Message}}"'
    context: 'files'
    prompts:
      - type: 'input'
        title: 'WIP message:'
        key: 'Message'
        initialValue: 'work in progress'
    description: 'Quick WIP commit'

# Keybindings (vim-like optimized)
keybinding:
  universal:
    quit: 'q'
    quit-alt1: '<c-c>'
    return: '<esc>'
    quitWithoutChangingDirectory: 'Q'
    togglePanel: '<tab>'
    prevItem: '<up>'
    nextItem: '<down>'
    prevItem-alt: 'k'
    nextItem-alt: 'j'
    prevPage: ','
    nextPage: '.'
    scrollLeft: 'H'
    scrollRight: 'L'
    gotoTop: '<'
    gotoBottom: '>'
    prevBlock: '<left>'
    nextBlock: '<right>'
    prevBlock-alt: 'h'
    nextBlock-alt: 'l'
    nextBlock-alt2: '<tab>'
    prevBlock-alt2: '<backtab>'
    jumpToBlock: ['1', '2', '3', '4', '5']
    nextMatch: 'n'
    prevMatch: 'N'
    startSearch: '/'
    optionMenu: 'x'
    optionMenu-alt1: '?'
    select: '<space>'
    goInto: '<enter>'
    confirm: '<enter>'
    confirmInEditor: '<a-enter>'
    remove: 'd'
    new: 'a'
    edit: 'e'
    openFile: 'o'
    scrollUpMain: '<pgup>'
    scrollDownMain: '<pgdown>'
    scrollUpMain-alt1: 'K'
    scrollDownMain-alt1: 'J'
    scrollUpMain-alt2: '<c-u>'
    scrollDownMain-alt2: '<c-d>'
    executeCustomCommand: ':'
    createRebaseOptionsMenu: 'm'
    pushFiles: 'P'
    pullFiles: 'p'
    refresh: 'R'
    createPatchOptionsMenu: '<c-p>'
    nextTab: ']'
    prevTab: '['
    nextScreenMode: '+'
    prevScreenMode: '_'
    undo: 'z'
    redo: '<c-z>'
    filteringMenu: '<c-s>'
    diffingMenu: 'W'
    diffingMenu-alt: '<c-e>'
    copyToClipboard: '<c-o>'
    openRecentRepos: '<c-r>'
    submitEditorText: '<enter>'
    extrasMenu: '@'
    toggleWhitespaceInDiffView: '<c-w>'
    increaseContextInDiffView: '}'
    decreaseContextInDiffView: '{'

  status:
    checkForUpdate: 'u'
    recentRepos: '<enter>'

  files:
    commitChanges: 'c'
    commitChangesWithoutHook: 'w'
    amendLastCommit: 'A'
    commitChangesWithEditor: 'C'
    findBaseCommitForFixup: '<c-f>'
    confirmDiscard: 'x'
    ignoreFile: 'i'
    refreshFiles: 'r'
    stashAllChanges: 's'
    viewStashOptions: 'S'
    toggleStagedAll: 'a'
    viewResetOptions: 'D'
    fetch: 'f'
    toggleTreeView: '`'
    openMergeTool: 'M'
    openStatusFilter: '<c-b>'

  branches:
    createPullRequest: 'o'
    viewPullRequestOptions: 'O'
    copyPullRequestURL: '<c-y>'
    checkoutBranchByName: 'c'
    forceCheckoutBranch: 'F'
    rebaseBranch: 'r'
    renameBranch: 'R'
    mergeIntoCurrentBranch: 'M'
    viewGitFlowOptions: 'i'
    fastForward: 'f'
    createTag: 'T'
    pushTag: 'P'
    setUpstream: 'u'
    fetchRemote: 'f'

  commits:
    squashDown: 's'
    renameCommit: 'r'
    renameCommitWithEditor: 'R'
    viewResetOptions: 'g'
    markCommitAsFixup: 'f'
    createFixupCommit: 'F'
    squashAboveCommits: 'S'
    moveDownCommit: '<c-j>'
    moveUpCommit: '<c-k>'
    amendToCommit: 'A'
    pickCommit: 'p'
    revertCommit: 't'
    cherryPickCopy: 'c'
    cherryPickCopyRange: 'C'
    pasteCommits: 'v'
    tagCommit: 'T'
    checkoutCommit: '<space>'
    resetCherryPick: '<c-R>'
    copyCommitMessageToClipboard: '<c-y>'
    openLogMenu: '<c-l>'
    viewBisectOptions: 'b'

  stash:
    popStash: 'g'
    renameStash: 'r'

  commitFiles:
    checkoutCommitFile: 'c'

  main:
    toggleSelectHunk: 'a'
    pickBothHunks: 'b'

  submodules:
    init: 'i'
    update: 'u'
    bulkMenu: 'b'